Lab8 Angular and Django/Django/shop_back/api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('', views.index, name='index'),
    path('products', views.products, name='products'),
    path('products/<int:id>/', views.a_product, name='a_product'),
    path('categories/', views.categories, name='categories'),
    path('categories/<int:id>/', views.a_category, name='a_category'),
    path('categories/<int:id>/products', views.get_by_category, name='get_by_category'),
]

Lab8 Angular and Django/Django/shop_back/shop_back/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

Lab8 Angular and Django/Django/shop_back/api/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    description = models.TextField()
    count = models.IntegerField(default=0)
    category = models.CharField(max_length=100, default="None")
    is_active = models.BooleanField()

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'price': self.price,
            'description': self.description,
            'count': self.count,
            'category': self.category,
            'is_active': self.is_active
        }

class Category(models.Model):
    name = models.CharField(max_length=50)

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name
        }

Lab8 Angular and Django/Django/shop_back/api/views.py
import tokenize

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, Http404
from django.template import loader
from .models import Product, Category

def index(request):
    return render(request, 'api/index.html',locals())

def products(request):
    prods = Product.objects.all()
    '''
    template = loader.get_template('api/products.html')
    context = {
        'prods': prods
    }
    '''
    #return HttpResponse(template.render(context,request))
    return JsonResponse([i.to_json() for i in prods], safe=False)


def a_product(request, id):
    try:
        product = Product.objects.get(id=id)
    except Product.DoesNotExist as e:
        raise Http404("Product does not exist")
    #return render(request, 'api/a_product.html',{'product':product})
    return JsonResponse(product.to_json())


def categories(request):
    categs = Category.objects.all()
    context = {'categs':categs}
    #return render(request, 'api/categories.html', context) #JsonResponse(categs_json, safe=False)
    return JsonResponse([i.to_json() for i in categs], safe=False)


def a_category(request, id):
    try:
        categ = Category.objects.get(id=id)
    except Category.DoesNotExist as e:
        return Http404("Category does not exist")
    #return render(request, 'api/a_category.html', {'category' : categ})
    return JsonResponse(categ.to_json())

def get_by_category(request, id):
    try:
        categ = Category.objects.get(id=id)
        products = Product.objects.filter(category=categ.name)
    except Category.DoesNotExist as e:
        return Http404("Category is empty")
    #return render(request, 'api/products.html', {'prods':products})
    return JsonResponse([i.to_json() for i in products], safe=False)


Lab8 Angular and Django/Django/shop_back/api/templates/api/a_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{category.name}}</h1>
    <a href="{% url 'api:get_by_category' category.id %}">See products...</a>
</body>
</html>

Lab8 Angular and Django/Django/shop_back/api/templates/api/a_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if product.is_active %}
        <h1>{{product.name}}</h1>
        <h2>{{product.price}}</h2>
        <p>{{product.description}}</p>
        <h3>{{product.count}}</h3>
    {% else %}
        <p>No product is not active now</p>
    {% endif %}
</body>
</html>

Lab8 Angular and Django/Django/shop_back/api/templates/api/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if categs %}
        <ul>
        {% for category in categs %}
            <li><a href="{% url 'api:a_category' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No categories are available.</p>
    {% endif %}
</body>
</html>

Lab8 Angular and Django/Django/shop_back/api/templates/api/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p></p><a href="{% url 'api:products' %}"> All Products </a></p>
    <p><a href="{% url 'api:categories' %}"> Categories </a></p>
</body>
</html>

Lab8 Angular and Django/Django/shop_back/api/templates/api/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% if prods %}
        <ul>
        {% for product in prods %}
            <li><a href="{% url 'api:a_product' product.id %}">{{ product.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No products are available.</p>
    {% endif %}

</body>
</html>